project_id = "mjrjvomvlymansybkmjf"

[functions.translate]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.generate-image-prompts]
verify_jwt = false

[functions.generate-video-image]
verify_jwt = false